/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniaturesimulator;

import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import miniaturesimulator.Units.CPU;

/**
 *
 * @author FARINAM
 */
public class Display extends javax.swing.JFrame {
    private CPU cpu= new CPU();
    
    

    /**
     * Creates new form Display
     */
    public Display() {
        initComponents();
        setIconImage(Button_Initialize,Button_Run,Button_StepRun);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel = new javax.swing.JPanel();
        Button_Initialize = new javax.swing.JButton();
        R1_label = new java.awt.Label();
        R3_label = new java.awt.Label();
        R2_label = new java.awt.Label();
        R5_label = new java.awt.Label();
        R4_label = new java.awt.Label();
        R6_label = new java.awt.Label();
        R8_label = new java.awt.Label();
        R7_label = new java.awt.Label();
        R0_label = new java.awt.Label();
        R9_label7 = new java.awt.Label();
        R10_label = new java.awt.Label();
        R12_label = new java.awt.Label();
        R11_label = new java.awt.Label();
        R14_label = new java.awt.Label();
        R13_label = new java.awt.Label();
        R15_label = new java.awt.Label();
        Button_StepRun = new javax.swing.JButton();
        Button_Run = new javax.swing.JButton();
        MemoryUsage_label = new javax.swing.JLabel();
        RegUsage_label = new javax.swing.JLabel();
        RegUsage = new javax.swing.JLabel();
        MemoryUsage = new javax.swing.JLabel();
        R0 = new javax.swing.JLabel();
        R1 = new javax.swing.JLabel();
        R2 = new javax.swing.JLabel();
        R3 = new javax.swing.JLabel();
        R4 = new javax.swing.JLabel();
        R5 = new javax.swing.JLabel();
        R6 = new javax.swing.JLabel();
        R7 = new javax.swing.JLabel();
        R8 = new javax.swing.JLabel();
        R9 = new javax.swing.JLabel();
        R10 = new javax.swing.JLabel();
        R11 = new javax.swing.JLabel();
        R12 = new javax.swing.JLabel();
        R13 = new javax.swing.JLabel();
        R14 = new javax.swing.JLabel();
        R15 = new javax.swing.JLabel();
        MemoryUsage_label1 = new javax.swing.JLabel();
        TotalInstructions = new javax.swing.JLabel();
        RunnedInstructions = new javax.swing.JLabel();
        RunnedInstructions_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Panel.setBackground(new java.awt.Color(203, 213, 224));
        Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 63, 105), 2));

        Button_Initialize.setBackground(java.awt.SystemColor.activeCaptionText);
        Button_Initialize.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        Button_Initialize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_InitializeActionPerformed(evt);
            }
        });

        R1_label.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        R1_label.setForeground(new java.awt.Color(61, 66, 97));
        R1_label.setText("R1       =");

        R3_label.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        R3_label.setForeground(new java.awt.Color(61, 66, 97));
        R3_label.setName(""); // NOI18N
        R3_label.setText("R3       =");

        R2_label.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        R2_label.setForeground(new java.awt.Color(61, 66, 97));
        R2_label.setText("R2       =");

        R5_label.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        R5_label.setForeground(new java.awt.Color(61, 66, 97));
        R5_label.setText("R5       =");

        R4_label.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        R4_label.setForeground(new java.awt.Color(61, 66, 97));
        R4_label.setText("R4       =");

        R6_label.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        R6_label.setForeground(new java.awt.Color(61, 66, 97));
        R6_label.setText("R6       =");

        R8_label.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        R8_label.setForeground(new java.awt.Color(61, 66, 97));
        R8_label.setText("R8       =");

        R7_label.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        R7_label.setForeground(new java.awt.Color(61, 66, 97));
        R7_label.setText("R7       =");

        R0_label.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        R0_label.setForeground(new java.awt.Color(61, 66, 97));
        R0_label.setText("R0       =");

        R9_label7.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        R9_label7.setForeground(new java.awt.Color(61, 66, 97));
        R9_label7.setText("R9       =");

        R10_label.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        R10_label.setForeground(new java.awt.Color(61, 66, 97));
        R10_label.setText("R10    =");

        R12_label.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        R12_label.setForeground(new java.awt.Color(61, 66, 97));
        R12_label.setText("R12    =");

        R11_label.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        R11_label.setForeground(new java.awt.Color(61, 66, 97));
        R11_label.setText("R11    =");

        R14_label.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        R14_label.setForeground(new java.awt.Color(61, 66, 97));
        R14_label.setText("R14    =");

        R13_label.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        R13_label.setForeground(new java.awt.Color(61, 66, 97));
        R13_label.setText("R13    =");

        R15_label.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 12)); // NOI18N
        R15_label.setForeground(new java.awt.Color(61, 66, 97));
        R15_label.setText("R15    =");

        Button_StepRun.setBackground(new java.awt.Color(153, 153, 153));
        Button_StepRun.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        Button_StepRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_StepRunActionPerformed(evt);
            }
        });

        Button_Run.setBackground(new java.awt.Color(153, 153, 153));
        Button_Run.setFont(new java.awt.Font("Eras Demi ITC", 0, 12)); // NOI18N
        Button_Run.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RunActionPerformed(evt);
            }
        });

        MemoryUsage_label.setFont(new java.awt.Font("Constantia", 1, 11)); // NOI18N
        MemoryUsage_label.setText("Memory  Usage   :");

        RegUsage_label.setFont(new java.awt.Font("Constantia", 1, 11)); // NOI18N
        RegUsage_label.setText("Registers Usage   :");

        RegUsage.setBackground(new java.awt.Color(102, 102, 102));
        RegUsage.setText("0");

        MemoryUsage.setBackground(new java.awt.Color(102, 102, 102));
        MemoryUsage.setText("0");

        R0.setBackground(new java.awt.Color(102, 102, 102));
        R0.setText("0");

        R1.setBackground(new java.awt.Color(102, 102, 102));
        R1.setText("0");

        R2.setBackground(new java.awt.Color(102, 102, 102));
        R2.setText("0");

        R3.setBackground(new java.awt.Color(102, 102, 102));
        R3.setText("0");

        R4.setBackground(new java.awt.Color(102, 102, 102));
        R4.setText("0");

        R5.setBackground(new java.awt.Color(102, 102, 102));
        R5.setText("0");

        R6.setBackground(new java.awt.Color(102, 102, 102));
        R6.setText("0");

        R7.setBackground(new java.awt.Color(102, 102, 102));
        R7.setText("0");

        R8.setBackground(new java.awt.Color(102, 102, 102));
        R8.setText("0");

        R9.setBackground(new java.awt.Color(102, 102, 102));
        R9.setText("0");

        R10.setBackground(new java.awt.Color(102, 102, 102));
        R10.setText("0");

        R11.setBackground(new java.awt.Color(102, 102, 102));
        R11.setText("0");

        R12.setBackground(new java.awt.Color(102, 102, 102));
        R12.setText("0");

        R13.setBackground(new java.awt.Color(102, 102, 102));
        R13.setText("0");

        R14.setBackground(new java.awt.Color(102, 102, 102));
        R14.setText("0");

        R15.setBackground(new java.awt.Color(102, 102, 102));
        R15.setText("0");

        MemoryUsage_label1.setFont(new java.awt.Font("Constantia", 1, 11)); // NOI18N
        MemoryUsage_label1.setText("Total Instructions  :");

        TotalInstructions.setBackground(new java.awt.Color(102, 102, 102));
        TotalInstructions.setText("0");

        RunnedInstructions.setBackground(new java.awt.Color(102, 102, 102));
        RunnedInstructions.setText("0");

        RunnedInstructions_label.setFont(new java.awt.Font("Constantia", 1, 11)); // NOI18N
        RunnedInstructions_label.setText("Runned Instructions  :");

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(R6_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(R11_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(R10_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(R12_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(R13_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(R14_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(R15_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(R9_label7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(R8_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(R7_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(R5_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R4_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R3_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R2_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R1_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R0_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(R14, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R13, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegUsage_label)
                            .addComponent(MemoryUsage_label)
                            .addComponent(RunnedInstructions_label)
                            .addComponent(MemoryUsage_label1))
                        .addGap(30, 30, 30)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TotalInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(MemoryUsage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(RegUsage, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(RunnedInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Button_StepRun, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Initialize, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Run, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RegUsage_label)
                            .addComponent(RegUsage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MemoryUsage_label)
                            .addComponent(MemoryUsage))
                        .addGap(6, 6, 6)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RunnedInstructions_label)
                            .addComponent(RunnedInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MemoryUsage_label1)
                            .addComponent(TotalInstructions))
                        .addGap(25, 25, 25)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(R0)
                            .addComponent(R0_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(R1_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R1)))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(Button_Initialize, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Button_Run, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(R2_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(R3_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R3)))
                    .addComponent(Button_StepRun, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(R4_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addComponent(R5_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(R6_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(R6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(R7_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(R7)))
                            .addComponent(R5)))
                    .addComponent(R4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(R8_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addComponent(R9_label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(R10_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R10))
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(R11_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(R11)
                                .addGap(14, 14, 14)))
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(R12)
                            .addComponent(R12_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(R13_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(R14_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(R14)))
                    .addComponent(R9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(R15_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(R15))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setIconImage(JButton Button_Initialize1, JButton Button_Run1, JButton Button_StepRun1) {
    Button_Initialize1.setIcon(new ImageIcon ("buttonpic\\button_initialize.png"));
    Button_Run1.setIcon(new ImageIcon ("buttonpic\\button_run.png"));
    Button_StepRun1.setIcon(new ImageIcon ("buttonpic\\button_step-run.png"));
    }
    private void Button_InitializeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_InitializeActionPerformed
        
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String path = f.getAbsolutePath();
        cpu.initialize(path);
    }//GEN-LAST:event_Button_InitializeActionPerformed

    private void Button_StepRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_StepRunActionPerformed
        
        cpu.runCompletely();
        regTable();
        usage();
    }//GEN-LAST:event_Button_StepRunActionPerformed

    private void Button_RunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RunActionPerformed
        
        cpu.run1Step();
        regTable();
        usage();
    }//GEN-LAST:event_Button_RunActionPerformed
    private void regTable (){
        int[] regs=null ; //= cpu.regs ;
        R0.setText(regs[0]+"");
        R1.setText(regs[1]+"");
        R2.setText(regs[2]+"");
        R3.setText(regs[3]+"");
        R4.setText(regs[4]+"");
        R5.setText(regs[5]+"");
        R6.setText(regs[6]+"");
        R7.setText(regs[7]+"");
        R8.setText(regs[8]+"");
        R9.setText(regs[9]+"");
        R10.setText(regs[10]+"");
        R11.setText(regs[11]+"");
        R12.setText(regs[12]+"");
        R13.setText(regs[13]+"");
        R14.setText(regs[14]+"");
        R15.setText(regs[15]+"");
        
        
    }
    private void usage (){
        
        RegUsage.setText(cpu.registersUsed()+"");
        MemoryUsage.setText(cpu.memortyUsed()+"");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Display.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Display().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Initialize;
    private javax.swing.JButton Button_Run;
    private javax.swing.JButton Button_StepRun;
    private javax.swing.JLabel MemoryUsage;
    private javax.swing.JLabel MemoryUsage_label;
    private javax.swing.JLabel MemoryUsage_label1;
    private javax.swing.JPanel Panel;
    private javax.swing.JLabel R0;
    private java.awt.Label R0_label;
    private javax.swing.JLabel R1;
    private javax.swing.JLabel R10;
    private java.awt.Label R10_label;
    private javax.swing.JLabel R11;
    private java.awt.Label R11_label;
    private javax.swing.JLabel R12;
    private java.awt.Label R12_label;
    private javax.swing.JLabel R13;
    private java.awt.Label R13_label;
    private javax.swing.JLabel R14;
    private java.awt.Label R14_label;
    private javax.swing.JLabel R15;
    private java.awt.Label R15_label;
    private java.awt.Label R1_label;
    private javax.swing.JLabel R2;
    private java.awt.Label R2_label;
    private javax.swing.JLabel R3;
    private java.awt.Label R3_label;
    private javax.swing.JLabel R4;
    private java.awt.Label R4_label;
    private javax.swing.JLabel R5;
    private java.awt.Label R5_label;
    private javax.swing.JLabel R6;
    private java.awt.Label R6_label;
    private javax.swing.JLabel R7;
    private java.awt.Label R7_label;
    private javax.swing.JLabel R8;
    private java.awt.Label R8_label;
    private javax.swing.JLabel R9;
    private java.awt.Label R9_label7;
    private javax.swing.JLabel RegUsage;
    private javax.swing.JLabel RegUsage_label;
    private javax.swing.JLabel RunnedInstructions;
    private javax.swing.JLabel RunnedInstructions_label;
    private javax.swing.JLabel TotalInstructions;
    // End of variables declaration//GEN-END:variables
}
